
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import logic.*;
import java.util.*;

/**
 *
 * @author celia
 */
public class VentanaActividadesAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaActividadesAdmin.class.getName());
    private Gimnasio gimnasio;
    private ArrayList<Actividad> actividades;
    private VentanaActividadesAdmin vent;
    private Actividad actividadAEditar;

    /**
     * Creates new form VentanaActividades
     */
    public VentanaActividadesAdmin(Gimnasio gimnasio) {
        initComponents();
        this.gimnasio = gimnasio;
        this.setLocationRelativeTo(null);
        mostrarListaActividades();
    }

    public void mostrarListaActividades() {
        txtListadoActividades.setText("");
        for (Actividad a : gimnasio.getActividades()) {
            txtListadoActividades.append(a.toString() + "\n");
            txtListadoActividades.append("\n---------------------\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverAdmin = new javax.swing.JButton();
        nombreActividad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListadoActividades = new javax.swing.JTextArea();
        btnModificarActividad = new javax.swing.JButton();
        btnAñadirActividad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBorrarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        btnVolverAdmin.setBackground(new java.awt.Color(255, 204, 0));
        btnVolverAdmin.setText("VOLVER AL MENÚ DE ADMINISTRADOR");
        btnVolverAdmin.addActionListener(this::btnVolverAdminActionPerformed);

        txtListadoActividades.setColumns(20);
        txtListadoActividades.setRows(5);
        jScrollPane1.setViewportView(txtListadoActividades);

        btnModificarActividad.setBackground(new java.awt.Color(255, 204, 0));
        btnModificarActividad.setText("Modificar actividad");
        btnModificarActividad.addActionListener(this::btnModificarActividadActionPerformed);

        btnAñadirActividad.setBackground(new java.awt.Color(255, 204, 0));
        btnAñadirActividad.setText("Añadir actividad");
        btnAñadirActividad.addActionListener(this::btnAñadirActividadActionPerformed);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Gestiona las actividades en este menú:");

        jLabel2.setText("Titulo:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setText("Introduce los datos de la actividad que quieras borrar:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiRecursos/logoPrincipal.png"))); // NOI18N

        btnBorrarActividad.setBackground(new java.awt.Color(255, 204, 0));
        btnBorrarActividad.setText("Borrar actividad");
        btnBorrarActividad.addActionListener(this::btnBorrarActividadActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnVolverAdmin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAñadirActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnModificarActividad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnBorrarActividad)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolverAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAñadirActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarActividad)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAdminActionPerformed
        VentanaAdmin ventA = new VentanaAdmin(gimnasio);
        ventA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAdminActionPerformed

    private void btnModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActividadActionPerformed

        String nombre = nombreActividad.getText();

        Actividad encontrada = null;
        for (Actividad a : gimnasio.getActividades()) {
            if (a.getTitulo().equalsIgnoreCase(nombre)) {
                encontrada = a;
                break;
            }
        }

        if (encontrada != null) {
            ModificaActividadAdmin mod = new ModificaActividadAdmin(gimnasio, encontrada);
            mod.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la actividad");
        }

    }//GEN-LAST:event_btnModificarActividadActionPerformed

    private void btnAñadirActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActividadActionPerformed
        AñadeActividadAdmin añadeAct = new AñadeActividadAdmin(gimnasio);
        añadeAct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAñadirActividadActionPerformed

    private void btnBorrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActividadActionPerformed
        String nombre = nombreActividad.getText();
        Actividad encontrada = null;

        for (Actividad a : gimnasio.getActividades()) {
            if (a.getTitulo().equalsIgnoreCase(nombre)) {
                encontrada = a;
                break;
            }
        }

        if (encontrada != null) {

            int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estas seguro de que quieres borrar la actividad " + nombre + "?");

            if (respuesta == 0) {//(si)
                gimnasio.getActividades().remove(encontrada);
                gimnasio.guardarDatos();
                mostrarListaActividades();
                javax.swing.JOptionPane.showMessageDialog(this, "Has eliminado la actividad " + nombre);
                nombreActividad.setText("");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la actividad");
        }
    }//GEN-LAST:event_btnBorrarActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirActividad;
    private javax.swing.JButton btnBorrarActividad;
    private javax.swing.JButton btnModificarActividad;
    private javax.swing.JButton btnVolverAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreActividad;
    private javax.swing.JTextArea txtListadoActividades;
    // End of variables declaration//GEN-END:variables
}
